
package infinotes.theory;

public enum Instrument{
	// Piano
	PIANO, ACOUSTIC_GRAND,
	BRIGHT_ACOUSTIC,
	ELECTRIC_GRAND,
	HONKEY_TONK,
	ELECTRIC_PIANO, ELECTRIC_PIANO1,
	ELECTRIC_PIANO2,
	HARPISCHORD,
	CLAVINET,
	
	// Chromatic Percussion
	CELESTA,
	GLOCKENSPIEL,
	MUSIC_BOX,
	VIBRAPHONE,
	MARIMBA,
	XYLOPHONE,
	TUBULAR_BELLS,
	DULCIMER,
	
	// Organ
	DRAWBAR_ORGAN,
	PERCUSSIVE_ORGAN,
	ROCK_ORGAN,
	CHURCH_ORGAN,
	REED_ORGAN,
	ACCORIDAN,
	HARMONICA,
	TANGO_ACCORDIAN,
	
	// Guitar
	GUITAR,
	NYLON_STRING_GUITAR,
	STEEL_STRING_GUITAR,
	ELECTRIC_JAZZ_GUITAR,
	ELECTRIC_CLEAN_GUITAR,
	ELECTRIC_MUTED_GUITAR,
	OVERDRIVEN_GUITAR,
	DISTORTION_GUITAR,
	GUITAR_HARMONICS,
	
	// Bass
	ACOUSTIC_BASS,
	ELECTRIC_BASS_FINGER,
	ELECTRIC_BASS_PICK,
	FRETLESS_BASS,
	SLAP_BASS_1,
	SLAP_BASS_2,
	SYNTH_BASS_1,
	SYNTH_BASS_2,
	
	// Strings
	VIOLIN,
	VIOLA,
	CELLO,
	CONTRABASS,
	TREMOLO_STRINGS,
	PIZZICATO_STRINGS,
	ORCHESTRAL_STRINGS,
	TIMPANI,
	
	// Ensemble
	STRING_ENSEMBLE_1,
	STRING_ENSEMBLE_2,
	SYNTH_STRINGS_1,
	SYNTH_STRINGS_2,
	CHOIR_AAHS,
	VOICE_OOHS,
	SYNTH_VOICE,
	ORCHESTRA_HIT,
	
	// Brass
	TRUMPET,
	TROMBONE,
	TUBA,
	MUTED_TRUMPET,
	FRENCH_HORN,
	BRASS_SECTION,
	SYNTHBRASS_1,
	SYNTHBRASS_2,
	
	// Reed
	SOPRANO_SAX,
	ALTO_SAX,
	TENOR_SAX,
	BARITONE_SAX,
	OBOE,
	ENGLISH_HORN,
	BASSOON,
	CLARINET,
	
	// Pipe
	PICCOLO,
	FLUTE,
	RECORDER,
	PAN_FLUTE,
	BLOWN_BOTTLE,
	SKAKUHACHI,
	WHISTLE,
	OCARINA,
	
	// Synth Lead
	LEAD_SQUARE, SQUARE,
	LEAD_SAWTOOTH, SAWTOOTH,
	LEAD_CALLIOPE, CALLIOPE,
	LEAD_CHIFF, CHIFF,
	LEAD_CHARANG, CHARANG,
	LEAD_VOICE, VOICE,
	LEAD_FIFTHS, FIFTHS,
	LEAD_BASSLEAD, BASSLEAD,
	
	// Synth Pad
	PAD_NEW_AGE, NEW_AGE,
	PAD_WARM, WARM,
	PAD_POLYSYNTH, POLYSYNTH,
	PAD_CHOIR, CHOIR,
	PAD_BOWED, BOWED,
	PAD_METALLIC, METALLIC,
	PAD_HALO, HALO,
	PAD_SWEEP, SWEEP,
	
	// Synth Effects
	FX_RAIN, RAIN,
	FX_SOUNDTRACK, SOUNDTRACK,
	FX_CRYSTAL,	CRYSTAL,
	FX_ATMOSPHERE, ATMOSPHERE,
	FX_BRIGHTNESS, BRIGHTNESS,
	FX_GOBLINS,	GOBLINS,
	FX_ECHOES, ECHOES,
	FX_SCI_FI, SCI_FI,
	
	// Ethnic
	SITAR,
	BANJO,
	SHAMISEN,
	KOTO,
	KALIMBA,
	BAGPIPE,
	FIDDLE,
	SHANAI,
	
	// Percussive
	TINKLE_BELL,
	AGOGO,
	STEEL_DRUMS,
	WOODBLOCK,
	TAIKO_DRUM,
	MELODIC_TOM,
	SYNTH_DRUM,
	REVERSE_CYMBAL,
	
	// Sound Effects
	GUITAR_FRET_NOISE,
	BREATH_NOISE,
	SEASHORE,
	BIRD_TWEET,
	TELEPHONE_RING,
	HELICOPTER,
	APPLAUSE,
	GUNSHOT;
}